### ISSUE TITLE
Pick locale based on users browser automatically rather than fetching the locale definitions

### ISSUE THREAD

**Issue by AbeykoonOshan** [d3/d3-format#122]
At the moment, d3 doesn't support to pick the locale based on user's browser. It will be great if we can support this feature by default rather picking U.S English as the default locale.

**Comment by Fil** [comment]
I strongly recommend **against** this — since it would mean that a chart written in English and displayed within an English-language page would appear (on my browser) with French numbers.

This would: 
* be confusing and inconsistent (why translate only the number format?)
* create unpredictable side effects (potentially breaking the chart altogether if the developer does something more than just displaying anything the format returns, and hasn't tested that in all the world's languages)
* lead to errors in reading data values: "1,111" in an English chart means one thousand one hundred eleven, and in a French chart means one point one hundred eleven.

Of course some tools can be fully localized. But in that case, I think the right approach is to use the browser locale to set the default language of the application (by selecting the closest language to the browser locale that the application supports), and then to allow the user to select another language if they want.

**Comment by mbostock** [comment]
Agreed with @Fil. Also, JavaScript’s built-in localization has dramatically improved since d3-format was created, so in the long run I think most if not all people should switch to that.

https://observablehq.com/@mbostock/number-formatting
