### ISSUE TITLE
Adding a parse method

### ISSUE THREAD

**Issue by SylvainCorlay** [d3/d3-format#20]
Like in `d3-time-format`, adding a parse method to the number formatters could be useful to get a number back when the representation is not a valid argument to construct numbers

``` JacaScript
var format = d3.formatPrefix(",.0", 1e-6);
format(0.00042); // "420µ"
format.parse("420µ"); // 0.00042
```

**Comment by Lacroute** [comment]
I agree. I'm facing this problem: I want to tween text during the update of my data. The text is in a localized percentage format.

I'm following this pattern https://bl.ocks.org/mbostock/7004f92cac972edef365. For now I got the choice between always tween from 0 to my target value, or try to parse with some RegExps the `self.text()` result.

It would be simpler and safer to have a `parse` method instead of a `string.replace`.

**Comment by jainswapnil90** [comment]
I have a doubt on new formatting style in version 4.
**console.log(d3.format(",.1f")(-0.03233401761776867))**
when I am consoling this in version 3 Output : -0.0
But in version 4 it is coming as 0.0
How to fix this issue ??

http://bl.ocks.org/zanarmstrong/raw/05c1e95bf7aa16c4768e/ version 3 output test case

**Comment by mbostock** [comment]
@jainswapnil90 Please don’t reply to unrelated issues with help requests. Use Stack Overflow to ask for help. The behavior you describe is documented in the [release notes for 1.0](https://github.com/d3/d3-format/releases/tag/v1.0.0) and 0.0 is the expected behavior in 4.0.

**Comment by mbostock** [comment]
Closing to inactivity. I have no immediate plans to implement parsers for localized number formats (and I think that would be a lot of work!).
