### ISSUE TITLE
"+" format adds a plus sign to zero

### ISSUE THREAD

**Issue by druvisc** [d3/d3-format#46]
Just like the title says - the "+" formatting adds a plus sign to 0, turning it into "+0" (https://jsfiddle.net/b7g9r739/). I'm using it to display the plus sign for positive values. Is this the correct behaviour?

[Here](https://github.com/d3/d3-format/blob/master/README.md#locale_format) it says:

> a plus sign for positive and a minus sign for negative.

**Comment by druvisc** [comment]
On a side note for another question regarding intended behaviour. Some time ago I ran into [this](https://jsfiddle.net/bL0qoa5e/) (leading zero for si prefix), which I wasn't expecting.

**Comment by mbostock** [comment]
Yes, this is the expected behavior. I’ll make a small clarification in the README.

Regarding your second comment, what behavior did you expect? Your format is `,.2s`, which means you’ll get two significant digits with SI-prefix formatting. Therefore 1.01 is rounded to 1.0e0 and displayed as 1.0, and 0.01 is rounded to 1.0e-2 and displayed as 10m. If you think you’ve found a bug, please file a separate issue and specify both the expected and the observed behavior in the description (along with a link to live code to reproduce the observed behavior, as you’ve done).

Also, if you want to ask for help, please use [Stack Overflow tag d3.js](https://stackoverflow.com/tags/d3.js). If you have a question about D3’s behavior and want to discuss it with other users, also consider the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or [joining](https://d3-slackin.herokuapp.com/) the [d3-js Slack](https://d3js.slack.com/).

Thank you! 🤗
