### ISSUE TITLE
Use N/A instead of NaN by default?

### ISSUE THREAD

**Issue by DavidBruant** [d3/d3-format#47]
I'm writing an application that displays something before the data is here. The data is lots of numbers and sometimes they're not there yet (waiting for network latency), so `undefined` is passed to be displayed. Transformed to a number, it yields `NaN`.
As it turns out, few humans understand what `NaN` means and why this text would show up in a screen (even worse with `text-transform: uppercase` both in English and French for different reasons). 

As a consequence, I believe an empty string would be a better formatting of `NaN` or `undefined` than `"NaN"` is.

Happy to send a PR if there is agreement here.
What do you think?

**Comment by robatwilliams** [comment]
D3 4.12.2:
```
d3.format('.2')(undefined) // "NaN"
d3.format('.2')(null) // "0"
d3.format('.2')(NaN) // "NaN"
```
These are the string representations of what `Number()` returns when given the above test values.

I don't think any chosen output would suit everyone in this case, so it would be best handled by wrapping the formatter.

`NaN` at least draws attention to missing data so you can do something about it - whether that be formatting expected missing data to empty string, or fixing a bug that results in unexpectedly missing data. Perhaps a change could be made to draw attention to the `null` case in the same way.

**Comment by mbostock** [comment]
Yes, the locale should be able to specify what to display for NaN input. For example in U.S. English I’d probably use "N/A" instead of "NaN". Likewise we might want to shortcircuit some of the formatting logic. For example this:

```js
d3.format('+%')(NaN)
```

Should probably return "N/A" (or "NaN"), not "+NaN%" as it currently does. But if the format has padding or alignment, that should probably be observed even while the value itself is formatted as "N/A".

**Comment by mbostock** [comment]
You can now localize NaN, but I’d like to switch to using N/A by default instead of NaN for the next major release, so repurposing this issue.
