### ISSUE TITLE
Feature idea for time formatter

### ISSUE THREAD

**Issue by villebro** [d3/d3-format#61]
On numerous occasions I've needed a formatter to change seconds into hh:mm:ss format, and googling indicates wider interest in a formatter to handle something similar. A few examples:

10 seconds: 0:10
100 seconds: 1:40
100.5 seconds: 1:40.5
100.5 seconds with 6 zero fills and rounding to zero decimals: 00:01:41

I this something that would fall within the scope of d3-format? While something similar can be accomplished with d3-time-format, I feel that this is more applicable to d3-format, as the underlying variable in this case is seconds, not a Date. If so I would be happy to write up a PR for the feature.

**Comment by mbostock** [comment]
This feels different enough from normal number formatting that I probably wouldn’t try to shoe-horn it into d3.format, and I would use a standalone implementation. I agree that d3-time-format also isn’t really the place for this because the input should be a number of milliseconds (not seconds, since milliseconds are the natural time unit in JavaScript). I’d probably call this a duration format.

**Comment by mbostock** [comment]
Closing as I have no immediate plans to implement this and think it would be best to start as a standalone module.

**Comment by villebro** [comment]
@thanks for the feedback @mbostock , will check again if someone has already done work in this area since this ticket; if not will probably see if I can build a sensible standalone implementation for this.
