### ISSUE TITLE
Precision error when there are 18 decimal places

### ISSUE THREAD

**Issue by tab00** [d3/d3-format#63]
`d3Format.format(".18f")(1.1)` gives `1.100000000000000089`
`d3Format.format(".18f")(1.2)` gives `1.199999999999999956`
`d3Format.format(".18f")(1.3)` gives `1.300000000000000044`

... etc. which are all wrong.

This package claims to fix the problem of binary floating point yet it seems to suffer from it.

Can this problem be fixed? Or is there an alternative package that is precise for many decimal places or large numbers?

I use the [bignumber.js](https://github.com/MikeMcl/bignumber.js) package for precise calculations with 18 decimal places, but it would be great to be able to format the results nicely for the UI.

**Comment by mbostock** [comment]
These are not wrong; these are the correct answers, because the number literal `1.1` in JavaScript is equal to 1.100000000000000089…, not 1.1. See http://0.30000000000000004.com/

JavaScript doesn’t have decimal floating point natively, but you could use a library like [big.js](http://mikemcl.github.io/big.js/) for arbitrary-precision decimal arithmetic.
