### ISSUE TITLE
d3-format fixed incorrectly rounds some numbers

### ISSUE THREAD

**Issue by futuraprime** [d3/d3-format#89]
When rounding positive and negative numbers, `Math.round` behaves according to mathematical convention:
```
> [40.5, -40.5].map(Math.round)
< (2) [41, -40]
```

However, this is not how `d3.format` behaves:
```
> [40.5, -40.5].map(d3.format('.0f'))
< ["41", "-41"]
```

Obviously, one can just use `Math.round` here, but if you're rounding to tenths or hundredths, using `Math.round(n * 10 ** p) / 10 ** p)` can introduce the same IEEE 754 rounding errors that d3-format is meant to fix. (`Number.toFixed(0)` produces the same result as d3, and it's unlikely JavaScript interpreters will fix that error.)

Negative numbers aren't the only place where d3.format has a problem with ambigious rounding: again following `Number.toFixed`, it will round up or down ambigious cases somewhat arbitrarily:
```
> [2.05, 2.15, 2.25, 2.35, 2.45, 2.55, 2.65, 2.75, 2.85, 2.95, 3.05].map(d3.format('.1f'))
< ["2.0", "2.1", "2.3", "2.4", "2.5", "2.5", "2.6", "2.8", "2.9", "3.0", "3.0"]
```

**Comment by futuraprime** [comment]
Sorry, no, I hadn't. I'd originally thought this was just to do with negative numbers so I missed it in my search.

Negative numbers do seem like they're a separate issue. 40.5 and -40.5 should both be exactly representable in binary, so I don't understand why d3 (and `toFixed`) should round -40.5 (or any other negative integer-and-a-half) down instead of up.

**Comment by mbostock** [comment]
I’ve confirmed that d3-format’s behavior is consistent with *number*.toFixed, which isn’t too surprising because that method is the basis of the `f` format type:

https://observablehq.com/d/7957bdfa735d20f0

And I took another look at the specification for *number*.toFixed, and while I don’t have a smoking gun to explain the behavior here, I expect the reason for this behavior is in 9a where *number*.toFixed is intended to be symmetric around zero (unlike Math.round, which rounds 0.5 up):

https://tc39.es/ecma262/#sec-number.prototype.tofixed
